{% set name = "drexml" %}
{% set version = "0.11.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/drexml-{{ version }}.tar.gz
  sha256: a55de1cfd64fe5b401dcc44f144da83473a53b92a0a5b4b8520af778f045b382

build:
  entry_points:
    - drexml = drexml.cli.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - pdm-backend
    - pip
  run:
    - python >=3.8,<3.11
    - scikit-learn >=1.3.0
    - numpy >=1.24.4
    - scipy >=1.10.1
    - pandas >=2.0.3
    - seaborn >=0.12.2
    - shap ==0.42.0
    - matplotlib-base >=3.7.2
    - python-dotenv >=1.0.0
    - pyarrow >=12.0.1
    - zenodo-client <0.3

test:
  imports:
    - drexml
  commands:
    - pip check
    - drexml --help
  requires:
    - pip

about:
  summary: (DRExM³L) Drug REpurposing using and eXplainable Machine Learning and Mechanistic Models of signal transduction"
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - loucerac
